import os
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'cytus.settings')
import django
django.setup()
from wiki.models import Category, Page
import random


def populate():
    # Chapter I
    category = addCategory('Chapter I')
    addPage(category, 'Alive: Operators', 'http://cytus.wikia.com/wiki/Alive:_Operators')
    addPage(category, 'Light up my LOVE', 'http://cytus.wikia.com/wiki/Light_up_my_LOVE')
    addPage(category, 'Ververg', 'http://cytus.wikia.com/wiki/Ververg')
    addPage(category, 'Ververg ver.B', 'http://cytus.wikia.com/wiki/Ververg ver.B')
    addPage(category, 'Chemical Star', 'http://cytus.wikia.com/wiki/Chemical_Star')
    addPage(category, 'Visions', 'http://cytus.wikia.com/wiki/Visions')
    addPage(category, 'Les Parfums de L,Amour', 'http://cytus.wikia.com/wiki/Les_Parfums_de_L%27Amour')
    addPage(category, 'Retrospective', 'http://cytus.wikia.com/wiki/Retrospective')
    addPage(category, 'The Silence', 'http://cytus.wikia.com/wiki/The_Silence')
    addPage(category, 'D R G', 'http://http://cytus.wikia.com/wiki/D_R_G')
    addPage(category, 'Secret Garden', 'http://cytus.wikia.com/wiki/Secret_Garden')
    addPage(category, 'Hot Air Balloon', 'http://cytus.wikia.com/wiki/Hot_Air_Balloon')
    # Chapter II
    category = addCategory('Chapter II')
    addPage(category, 'Alive: Disaster', 'http://cytus.wikia.com/wiki/Alive:_Disaster')
    addPage(category, 'Iris', 'http://cytus.wikia.com/wiki/Iris')
    addPage(category, 'Sanctity', 'http://cytus.wikia.com/wiki/Sanctity')
    addPage(category, 'Sacred', 'http://cytus.wikia.com/wiki/Sacred')
    addPage(category, 'Green Eyes', 'http://cytus.wikia.com/wiki/Green_Eyes')
    addPage(category, 'Nocturnal Type', 'http://cytus.wikia.com/wiki/Nocturnal_Type')
    addPage(category, 'Precipitation', 'http://cytus.wikia.com/wiki/Precipitation')
    addPage(category, 'Precipitation ver.B', 'http://cytus.wikia.com/wiki/Precipitation_ver.B')
    addPage(category, 'Hard Landing', 'http://cytus.wikia.com/wiki/Hard_Landing')
    addPage(category, 'Entrance', 'http://cytus.wikia.com/wiki/Entrance')
    addPage(category, 'Precipitation at the Entrance I', 'http://cytus.wikia.com/wiki/Precipitation_at_the_Entrance_I')
    addPage(category, 'Precipitation at the Entrance II', 'http://cytus.wikia.com/wiki/Precipitation_at_the_Entrance_II')
    # Chapter III
    category = addCategory('Chapter III')
    addPage(category, 'Alive: Cytus', 'http://cytus.wikia.com/wiki/Alive:_Cytus')
    addPage(category, 'The Riddle Story', 'http://cytus.wikia.com/wiki/The_Riddle_Story')
    addPage(category, 'Libera Me', 'http://cytus.wikia.com/wiki/Libera_Me')
    addPage(category, 'COSMO', 'http://cytus.wikia.com/wiki/COSMO')
    addPage(category, 'Prismatic Lolipops', 'http://cytus.wikia.com/wiki/Prismatic_Lollipops')
    addPage(category, 'Otome', 'http://cytus.wikia.com/wiki/Otome')
    addPage(category, 'Spectrum', 'http://cytus.wikia.com/wiki/Spectrum')
    addPage(category, 'Halcyon', 'http://cytus.wikia.com/wiki/Halcyon')
    addPage(category, 'The Black Case', 'http://cytus.wikia.com/wiki/The_Black_Case')
    addPage(category, 'Saika', 'http://cytus.wikia.com/wiki/Saika')
    addPage(category, 'Saika ver.B', 'http://cytus.wikia.com/wiki/Saika_ver.B')
    # Chapter IV
    category = addCategory('Chapter IV')
    addPage(category, 'Alive: The Silence', 'http://cytus.wikia.com/wiki/Alive:_The_Silence')
    addPage(category, 'Evil Force', 'http://cytus.wikia.com/wiki/Evil_Force')
    addPage(category, 'New World', 'http://cytus.wikia.com/wiki/New_World')
    addPage(category, 'Landscape', 'http://cytus.wikia.com/wiki/Landscape')
    addPage(category, 'Future World', 'http://cytus.wikia.com/wiki/Future_World')
    addPage(category, 'Parousia', 'http://cytus.wikia.com/wiki/Parousia')
    addPage(category, 'Skuld', 'http://cytus.wikia.com/wiki/Skuld')
    addPage(category, 'Darkness', 'http://cytus.wikia.com/wiki/Darkness')
    addPage(category, 'Beyond', 'http://cytus.wikia.com/wiki/Beyond')
    addPage(category, 'Area184', 'http://cytus.wikia.com/wiki/Area184')
    addPage(category, 'Sweetness And Love', 'http://cytus.wikia.com/wiki/Sweetness_And_Love')
    # Chapter V
    category = addCategory('Chapter V')
    addPage(category, 'Alive: Vanessa', 'http://cytus.wikia.com/wiki/Alive:_Vanessa')
    addPage(category, 'Holy Knight', 'http://cytus.wikia.com/wiki/Holy_Knight')
    addPage(category, 'Dino', 'http://cytus.wikia.com/wiki/Dino')
    addPage(category, 'Majestic Phoenix', 'http://cytus.wikia.com/wiki/Majestic_Phoenix')
    addPage(category, 'Sleepless Jasmine', 'http://cytus.wikia.com/wiki/Sleepless_Jasmine')
    addPage(category, 'Chocological', 'http://cytus.wikia.com/wiki/Chocological')
    addPage(category, 'Recollections', 'http://cytus.wikia.com/wiki/Recollections')
    addPage(category, 'Total Sphere', 'http://cytus.wikia.com/wiki/Total_Sphere')
    addPage(category, 'Just A Trip', 'http://cytus.wikia.com/wiki/Just_A_Trip')
    addPage(category, 'Zauberkugel', 'http://cytus.wikia.com/wiki/Zauberkugel')
    addPage(category, 'Biotonic', 'http://cytus.wikia.com/wiki/Biotonic')
    # Chapter VI
    category = addCategory('Chapter VI')
    addPage(category, 'Alive: The Lost', 'http://cytus.wikia.com/wiki/Alive:_The_Lost')
    addPage(category, 'Dragon Warrior', 'http://cytus.wikia.com/wiki/Dragon_Warrior')
    addPage(category, 'Selfish Gene', 'http://cytus.wikia.com/wiki/Selfish_Gene')
    addPage(category, 'Realize', 'http://cytus.wikia.com/wiki/Realize')
    addPage(category, 'Colorful Skies', 'http://cytus.wikia.com/wiki/Colorful_Skies')
    addPage(category, 'It,s A Wonderful World', 'http://cytus.wikia.com/wiki/It%27s_A_Wonderful_World')
    addPage(category, 'Bloody Purity', 'http://cytus.wikia.com/wiki/Bloody_Purity')
    addPage(category, 'Logical Steps', 'http://cytus.wikia.com/wiki/Logical_Steps')
    addPage(category, 'Niflheimr', 'http://cytus.wikia.com/wiki/Niflheimr')
    addPage(category, 'Old Gold', 'http://cytus.wikia.com/wiki/Old_Gold')
    addPage(category, 'The Block We Loved', 'http://cytus.wikia.com/wiki/The_Blocks_We_Loved')
    # Chapter VII
    category = addCategory('Chapter VII')
    addPage(category, 'Alive: Loom', 'http://cytus.wikia.com/wiki/Alive:_Loom')
    addPage(category, 'Black Lair', 'http://cytus.wikia.com/wiki/Black_Lair')
    addPage(category, 'The Last Illusion', 'http://cytus.wikia.com/wiki/The_Last_Illousion')
    addPage(category, 'Galaxy Collapse', 'http://cytus.wikia.com/wiki/Galaxy_Collapse')
    addPage(category, 'L', 'http://cytus.wikia.com/wiki/L')
    addPage(category, 'L2 - Ascension: Act 1 (Loneliness)', 'http://cytus.wikia.com/wiki/L2_-_Ascension:_Act_1_(Loneliness)')
    addPage(category, 'L2 - Ascension: Act 2 (Liberation)', 'http://cytus.wikia.com/wiki/L2_-_Ascension:_Act_2_(Liberation)')
    addPage(category, 'Gate of Expectancy', 'http://cytus.wikia.com/wiki/Gate_of_Exceptancy')
    addPage(category, 'Rainbow Night Sky Highway', 'http://cytus.wikia.com/wiki/Rainbow_Night_Sky_Highway')
    addPage(category, 'Quantum Labyrinth', 'http://cytus.wikia.com/wiki/Quantum_Labyrinth')
    addPage(category, 'Musik', 'http://cytus.wikia.com/wiki/Musik')
    addPage(category, 'Hercule', 'http://cytus.wikia.com/wiki/Hercule')
    addPage(category, 'Aquatic Poseidon', 'http://cytus.wikia.com/wiki/Aquatic Poseidon')
    # Chapter VIII
    category = addCategory('Chapter VIII')
    addPage(category, 'Alive: Another Me', 'http://cytus.wikia.com/wiki/Alive:_Another_Me')
    addPage(category, 'Masquerade', 'http://cytus.wikia.com/wiki/Masquerade')
    addPage(category, 'Her Sword', 'http://cytus.wikia.com/wiki/Her_Sword')
    addPage(category, 'Morpho', 'http://cytus.wikia.com/wiki/Morpho')
    addPage(category, '∅ (Slit)', 'http://cytus.wikia.com/wiki/∅_(Slit)')
    addPage(category, '∅ (Slit) O', 'http://cytus.wikia.com/wiki/∅_(Slit)_O')
    addPage(category, '∅ (Slit) I', 'http://cytus.wikia.com/wiki/∅_(Slit)_I')
    addPage(category, 'Laplace', 'http://cytus.wikia.com/wiki/Laplace')
    addPage(category, 'Q', 'http://cytus.wikia.com/wiki/Q')
    addPage(category, 'Scherzo', 'http://cytus.wikia.com/wiki/Scherzo')
    addPage(category, 'AXION', 'http://cytus.wikia.com/wiki/AXION')
    addPage(category, 'Code 03', 'http://cytus.wikia.com/wiki/Code_03')
    addPage(category, 'Reverence', 'http://cytus.wikia.com/wiki/Reverence')
    # Chapter IX
    category = addCategory('Chapter IX')
    addPage(category, 'Alive: Buried', 'http://cytus.wikia.com/wiki/Alive:_Buried')
    addPage(category, 'Oriens', 'http://cytus.wikia.com/wiki/Oriens')
    addPage(category, 'Hey Wonder', 'http://cytus.wikia.com/wiki/Hey_Wonder')
    addPage(category, 'Brionac', 'http://cytus.wikia.com/wiki/Brionac')
    addPage(category, 'First Gate', 'http://cytus.wikia.com/wiki/First_Gate')
    addPage(category, 'First Gate Overdrive', 'http://cytus.wikia.com/wiki/First_Gate_Overdrive')
    addPage(category, 'Qualia', 'http://cytus.wikia.com/wiki/Qualia')
    addPage(category, 'East West Wobble', 'http://cytus.wikia.com/wiki/East_West_Wobble')
    addPage(category, 'Warlords of Atlantis', 'http://cytus.wikia.com/wiki/Warlords_of_Atlantis')
    addPage(category, 'To Further Dream', 'http://cytus.wikia.com/wiki/To_Further_Dream')
    addPage(category, 'COMA', 'http://cytus.wikia.com/wiki/COMA')
    addPage(category, 'Codename: Zero', 'http://cytus.wikia.com/wiki/Codename_:_Zero')
    # Chapter X
    category = addCategory('Chapter X')
    addPage(category, 'Alive: The New World', 'http://cytus.wikia.com/wiki/Alive:The_New_World')
    addPage(category, 'Freedom Dive', 'http://cytus.wikia.com/wiki/Freedom_Dive')
    addPage(category, 'Halloween Party', 'http://cytus.wikia.com/wiki/Halloween_Party')
    addPage(category, 'YURERO', 'http://cytus.wikia.com/wiki/YURERO')
    addPage(category, 'Twenrt One', 'http://cytus.wikia.com/wiki/Twenty_One')
    addPage(category, 'Solar Wind', 'http://cytus.wikia.com/wiki/Solar_Wind')
    addPage(category, 'Red Eyes', 'http://cytus.wikia.com/wiki/Red_Eyes')
    addPage(category, 'Finite Circuit', 'http://cytus.wikia.com/wiki/Finite_Circuit')
    addPage(category, 'Set Free', 'http://cytus.wikia.com/wiki/Set_Free')
    addPage(category, 'Do Not Wake', 'http://cytus.wikia.com/wiki/Do_Not_Wake')
    addPage(category, 'Gatorix', 'http://cytus.wikia.com/wiki/Gatorix')
    # Chapter S
    category = addCategory('Chapter S')
    addPage(category, 'LVBNR5 Schwarz', 'http://cytus.wikia.com/wiki/LVBNR5_Schwarz')
    addPage(category, 'Vivere La Vita', 'http://cytus.wikia.com/wiki/Vivere_La_Vita')
    addPage(category, 'Rain of Fire', 'http://cytus.wikia.com/wiki/Rain_of_Fire')
    addPage(category, 'Molto Allegro', 'http://cytus.wikia.com/wiki/Molto_Allegro')
    addPage(category, 'Revoluxionist', 'http://cytus.wikia.com/wiki/Revoluxionist')
    addPage(category, 'LVBNR5 Weiβ', 'http://cytus.wikia.com/wiki/LVBNR5_Weiβ')
    addPage(category, 'Chaotic Drive', 'http://cytus.wikia.com/wiki/Chaotic_Drive')
    addPage(category, 'Outsider', 'http://cytus.wikia.com/wiki/Outsider')
    addPage(category, 'Requiem', 'http://cytus.wikia.com/wiki/Requiem')
    addPage(category, 'The Purified', 'http://cytus.wikia.com/wiki/The_Purified')
    # Chapter K
    category = addCategory('Chapter K')
    addPage(category, 'The Way We Were', 'http://cytus.wikia.com/wiki/The_Way_We_Were')
    addPage(category, 'The Sanctuary', 'http://cytus.wikia.com/wiki/The_Sanctuary')
    addPage(category, 'The Red Coronation', 'http://cytus.wikia.com/wiki/The_Red_Coronation')
    addPage(category, 'Forbidden Codex', 'http://cytus.wikia.com/wiki/Forbidden_Codex')
    addPage(category, 'Knight of Firmament', 'http://cytus.wikia.com/wiki/Knight_of_Firmament')
    addPage(category, 'Lord of Crimson Rose', 'http://cytus.wikia.com/wiki/Lord_of_Crimson_Rose')
    addPage(category, 'Predawn', 'http://cytus.wikia.com/wiki/Predawn')
    addPage(category, 'The Fallen Bloom', 'http://cytus.wikia.com/wiki/The_Fallen_Bloom')
    addPage(category, 'Where You Are Not', 'http://cytus.wikia.com/wiki/Where_You_Are_Not')
    addPage(category, 'Music. The Eternity of Us', 'http://cytus.wikia.com/wiki/Music._The_Eternity_of_Us')
    # Chapter R
    category = addCategory('Chapter R')
    addPage(category, 'Theme of Kingdom No.8', 'http://cytus.wikia.com/wiki/Theme_of_Kingdom_No.8')
    addPage(category, 'Jump To The Future', 'http://cytus.wikia.com/wiki/Jump_To_The_Future')
    addPage(category, 'Let,s Go On An Adventure', 'http://cytus.wikia.com/wiki/Let%27s_Go_On_An_Adventure')
    addPage(category, 'Hay Fields', 'http://cytus.wikia.com/wiki/Hay_Fields')
    addPage(category, 'Adventure', 'http://cytus.wikia.com/wiki/Adventure')
    addPage(category, 'Dream (Chiptune Edit)', 'http://cytus.wikia.com/wiki/Dream_(Chiptune_Edit)')
    addPage(category, 'VitMaster', 'http://cytus.wikia.com/wiki/VitMaster')
    addPage(category, 'Fight With Your Devil', 'http://cytus.wikia.com/wiki/Fight_With_Your_Devil')
    addPage(category, 'Devil in Wonderland', 'http://cytus.wikia.com/wiki/Devil_in_Wonderland')
    addPage(category, 'Conflict (YM2151 Edit)', 'http://cytus.wikia.com/wiki/Conflict_(YM2151_Edit)')
    addPage(category, 'Conflict', 'http://cytus.wikia.com/wiki/Conflict')
    # Chapter M
    category = addCategory('Chapter M')
    addPage(category, 'The Beginning', 'http://cytus.wikia.com/wiki/The_Beginning')
    addPage(category, 'Stardust Sphere', 'http://cytus.wikia.com/wiki/Stardust_Sphere')
    addPage(category, 'The Ricochet', 'http://cytus.wikia.com/wiki/The_Ricochet')
    addPage(category, 'The Long Years', 'http://cytus.wikia.com/wiki/The_Long_Years')
    addPage(category, 'The Sacred Story', 'http://cytus.wikia.com/wiki/The_Sacred_Story')
    addPage(category, 'Area184 -Platinum Mix-', 'http://cytus.wikia.com/wiki/Area184_-Platinum_Mix-')
    addPage(category, 'Gardenia', 'http://cytus.wikia.com/wiki/Gardenia')
    addPage(category, 'Sweetness Overload!!!', 'http://cytus.wikia.com/wiki/Sweetness_Overload!!!')
    addPage(category, 'Les Parfums de Celebrez', 'http://cytus.wikia.com/wiki/Les_Parfums_de_Celebrez')
    addPage(category, 'Afterglow', 'http://cytus.wikia.com/wiki/Afterglow')
    addPage(category, 'GENESYS', 'http://cytus.wikia.com/wiki/GENESYS')
    addPage(category, 'STROIA', 'http://cytus.wikia.com/wiki/STROIA')
    # Chapter T
    category = addCategory('Chapter T')
    addPage(category, 'Penglai Movement', 'http://cytus.wikia.com/wiki/Penglai_Movement')
    addPage(category, 'Aboriginal', 'http://cytus.wikia.com/wiki/Aboriginal')
    addPage(category, 'Dutch Formosa', 'http://cytus.wikia.com/wiki/Dutch_Formosa')
    addPage(category, 'Empire of Japan', 'http://cytus.wikia.com/wiki/Empire_of_Japan')
    addPage(category, 'Money & Money', 'http://cytus.wikia.com/wiki/Money_%26_Money')
    addPage(category, 'Phubbing', 'http://cytus.wikia.com/wiki/Phubbing')
    addPage(category, 'Protest', 'http://cytus.wikia.com/wiki/Protest')
    addPage(category, 'Catastrophe', 'http://cytus.wikia.com/wiki/Catastrophe')
    addPage(category, 'Rebirth', 'http://cytus.wikia.com/wiki/Rebirth')
    addPage(category, 'A New Home', 'http://cytus.wikia.com/wiki/A_New_Home')
    # Chapter D
    category = addCategory('Chapter D')
    addPage(category, 'Rainy Memory', 'http://cytus.wikia.com/wiki/Rainy_Memory')
    addPage(category, 'Undo', 'http://cytus.wikia.com/wiki/Undo')
    addPage(category, 'Hua Sui Yue', 'http://cytus.wikia.com/wiki/Hua_Sui_Yue')
    addPage(category, 'I Race The Dawn', 'http://cytus.wikia.com/wiki/I_race_the_dawn')
    addPage(category, 'Wings of Piano', 'http://cytus.wikia.com/wiki/Wings_of_Piano')
    addPage(category, 'Utopiosphere', 'http://cytus.wikia.com/wiki/Utopiosphere')
    addPage(category, 'Fable', 'http://cytus.wikia.com/wiki/Fable')
    addPage(category, 'Angelic Sphere', 'http://cytus.wikia.com/wiki/Angelic_Sphere')
    addPage(category, 'Leviathan', 'http://cytus.wikia.com/wiki/Leviathan')
    addPage(category, 'Magnolia', 'http://cytus.wikia.com/wiki/Magnolia')
    # Chapter L
    category = addCategory('Chapter L')
    addPage(category, 'L1:The Devastated Lower', 'http://cytus.wikia.com/wiki/L1:_The_Devastated_Lower')
    addPage(category, 'L2:Ascension To The Upper', 'http://cytus.wikia.com/wiki/L2_:_Ascension_To_The_Upper')
    addPage(category, 'L3:Roar, On The Deserted Lands', 'http://cytus.wikia.com/wiki/L3_:_Roar,_On_The_Deserted_Lands')
    addPage(category, 'L4:The Unrevealed', 'http://cytus.wikia.com/wiki/L4_:_The_Unrevealed')
    addPage(category, 'L5:The Revealed', 'http://cytus.wikia.com/wiki/L5_:_The_Revealed')
    addPage(category, 'L6:Viz Awakened', 'http://cytus.wikia.com/wiki/L6_:_Viz_Awakened')
    addPage(category, 'L7:Almighty', 'http://cytus.wikia.com/wiki/L7_:_Almighty')
    addPage(category, 'L8:Meteor - Farewell', 'http://cytus.wikia.com/wiki/L8_:_Meteor_-_Farewell')
    addPage(category, 'L9:Meteo - Mourn', 'http://cytus.wikia.com/wiki/L9_:_Meteo_-_Mourn')
    addPage(category, 'L10:In Memory of Maneo.', 'http://cytus.wikia.com/wiki/L10:_In_Memory_of_Maneo.')


    # Print everything
    for category in Category.objects.all():
        for page in Page.objects.filter(category=category):
            print(category.name, '--', page.title)
            
            
def addCategory(name):
    category = Category.objects.get_or_create(name=name)[0]
    return category
    
    
def addPage(category, title, url):
    page = Page.objects.get_or_create(category=category, title=title, url=url)[0]
    page.views = random.randint(0, 20)
    page.save()
        
        
if __name__ == '__main__':
    print('開始填入資料...')
    populate()
    print('完成。')